name: Prerelease

on:
  push:
    branches:
      - alpha
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build --if-present

      - name: Enter prerelease mode
        run: npx changeset pre enter dev

      - name: Version packages
        run: npx changeset version

      - name: Exit prerelease mode
        run: npx changeset pre exit

      - name: Create Prerelease PR or Publish with tag
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release --tag alpha
          title: "Prerelease: Version Packages (alpha)"
          commit: "Prerelease: Version Packages (alpha)"
        env:
          # Prefer a PAT to allow creating PRs when repo settings block the default token
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
