name: Release
on:
  push:
    branches:
      - main # or main
      - alpha # or alpha

permissions:
  contents: read # for checkout


jobs:
  release:
    name: Release CLI
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to ensure we can get all tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: npm install

      - name: Create Release PR / Publish
        uses: changesets/action@v1
        with:
          publish: npm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}